UPDATE suppliers SET name = 'HANSEL DNP, PT' WHERE id = 1;
UPDATE suppliers SET name = 'ANGUANG' WHERE id = 2;
UPDATE suppliers SET name = 'DOS NI ROHA, PT' WHERE id = 3;
UPDATE suppliers SET name = 'ANTARIKSA NIAGA' WHERE id = 4;
UPDATE suppliers SET name = 'LIM SIANG HUAT' WHERE id = 5;
UPDATE suppliers SET name = 'PT SELATINDO BA' WHERE id = 6;
UPDATE suppliers SET name = 'INDOMARCO' WHERE id = 7;
UPDATE suppliers SET name = 'COCA COLA DISTR' WHERE id = 8;
UPDATE suppliers SET name = 'INDOSINMA JAYA,' WHERE id = 9;
UPDATE suppliers SET name = 'SRIJAYA RAYA PE' WHERE id = 10;
UPDATE suppliers SET name = 'ABM' WHERE id = 11;
UPDATE suppliers SET name = 'SERAYA MAKMUR P' WHERE id = 12;
UPDATE suppliers SET name = 'PRIMA RINTIS SE' WHERE id = 13;
UPDATE suppliers SET name = 'ARTA BOGA CEMER' WHERE id = 14;
UPDATE suppliers SET name = 'PRINTIS PRIBADI' WHERE id = 15;
UPDATE suppliers SET name = 'BINTANG LIMA, P' WHERE id = 16;
UPDATE suppliers SET name = 'CV.WAHANA TIRTA' WHERE id = 17;
UPDATE suppliers SET name = 'PT ANUGRAH PERK' WHERE id = 18;
UPDATE suppliers SET name = 'ANUGERAH PERKAS' WHERE id = 19;
UPDATE suppliers SET name = 'DJEMBATAN DUA' WHERE id = 20;
UPDATE suppliers SET name = 'GEMBIRA' WHERE id = 21;
UPDATE suppliers SET name = 'PT KARYA CITRA' WHERE id = 22;
UPDATE suppliers SET name = 'PT MULTIBOGA A' WHERE id = 23;
UPDATE suppliers SET name = 'MITRA MANDIRI T' WHERE id = 24;
UPDATE suppliers SET name = 'PT.MULTIBOGA AR' WHERE id = 25;
UPDATE suppliers SET name = 'STARTMARA PRATA' WHERE id = 26;
UPDATE suppliers SET name = 'SNS.PT' WHERE id = 27;
UPDATE suppliers SET name = 'ERA' WHERE id = 28;
UPDATE suppliers SET name = 'BINTAN SUKSES M' WHERE id = 29;
UPDATE suppliers SET name = 'COLAMAS INDAH S' WHERE id = 30;
UPDATE suppliers SET name = 'CV. KIAT SEJAHT' WHERE id = 31;
UPDATE suppliers SET name = 'MESTIKA BATAM S' WHERE id = 32;
UPDATE suppliers SET name = 'PT PRIMA NIAGA' WHERE id = 33;
UPDATE suppliers SET name = 'PT AJINAMOTO SA' WHERE id = 34;
UPDATE suppliers SET name = 'AKP[ANUGRAH KAR' WHERE id = 35;
UPDATE suppliers SET name = 'LESTARI MANDIRI' WHERE id = 36;
UPDATE suppliers SET name = 'MULTI GLOBAL TR' WHERE id = 37;
UPDATE suppliers SET name = 'PT.YAFINDO MIT' WHERE id = 38;
UPDATE suppliers SET name = 'STAR MARA' WHERE id = 39;
UPDATE suppliers SET name = 'PD BINTANG BARU' WHERE id = 40;
UPDATE suppliers SET name = 'SUMBER SARI,CV' WHERE id = 41;
UPDATE suppliers SET name = 'GAJAH MADA' WHERE id = 42;
UPDATE suppliers SET name = 'BATAM PAPER CV' WHERE id = 43;
UPDATE suppliers SET name = 'PT MARGA NUSANT' WHERE id = 44;

UPDATE users SET role = 'Manajer' WHERE id = 1;